# Generated by Django 5.0.6 on 2024-07-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_objectlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectlog",
            name="object_id",
            field=models.CharField(max_length=50),
        ),
    ]
