# Generated by Django 5.0.6 on 2024-07-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0003_alter_objectlog_object_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectlog",
            name="username",
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
