# Generated by Django 5.0.6 on 2024-07-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0004_objectlog_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="abstract_field",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="objectlog",
            name="abstract_field",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="abstract_field",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
