# Generated by Django 5.0.6 on 2024-07-24 20:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0005_choice_abstract_field_objectlog_abstract_field_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="abstract_field",
        ),
        migrations.RemoveField(
            model_name="objectlog",
            name="abstract_field",
        ),
        migrations.RemoveField(
            model_name="question",
            name="abstract_field",
        ),
    ]
